/**
 * Generates a fresh event-session id.
 * Stamped on every transaction at checkout and regenerated by "Close Event",
 * so sales history stays grouped per event across DB resets-free operation.
 */
export const generateEventId = (): string =>
  `evt-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 6)}`;
